-- Insert dữ liệu tỉnh/thành phố
-- File: V7__insert_provinces_data.sql

INSERT INTO Provinces (ProvinceCode, ProvinceName, ProvinceNameEn, ProvinceFullName, ProvinceFullNameEn, CodeName) VALUES
('01', N'Hà Nội', 'Hanoi', N'Thành phố Hà Nội', 'Hanoi City', 'ha_noi'),
('79', N'TP Hồ Chí Minh', 'Ho Chi Minh City', N'Thành phố Hồ Chí Minh', 'Ho Chi Minh City', 'ho_chi_minh'),
('31', N'Hải Phòng', 'Hai Phong', N'Thành phố Hải Phòng', 'Hai Phong City', 'hai_phong'),
('48', N'Đà Nẵng', 'Da Nang', N'Thành phố Đà Nẵng', 'Da Nang City', 'da_nang'),
('92', N'Cần Thơ', 'Can Tho', N'Thành phố Cần Thơ', 'Can Tho City', 'can_tho'),

-- Tỉnh miền Bắc
('02', N'Hà Giang', 'Ha Giang', N'Tỉnh Hà Giang', 'Ha Giang Province', 'ha_giang'),
('04', N'Cao Bằng', 'Cao Bang', N'Tỉnh Cao Bằng', 'Cao Bang Province', 'cao_bang'),
('06', N'Bắc Kạn', 'Bac Kan', N'Tỉnh Bắc Kạn', 'Bac Kan Province', 'bac_kan'),
('08', N'Tuyên Quang', 'Tuyen Quang', N'Tỉnh Tuyên Quang', 'Tuyen Quang Province', 'tuyen_quang'),
('10', N'Lào Cai', 'Lao Cai', N'Tỉnh Lào Cai', 'Lao Cai Province', 'lao_cai'),
('11', N'Điện Biên', 'Dien Bien', N'Tỉnh Điện Biên', 'Dien Bien Province', 'dien_bien'),
('12', N'Lai Châu', 'Lai Chau', N'Tỉnh Lai Châu', 'Lai Chau Province', 'lai_chau'),
('14', N'Sơn La', 'Son La', N'Tỉnh Sơn La', 'Son La Province', 'son_la'),
('15', N'Yên Bái', 'Yen Bai', N'Tỉnh Yên Bái', 'Yen Bai Province', 'yen_bai'),
('17', N'Hoà Bình', 'Hoa Binh', N'Tỉnh Hoà Bình', 'Hoa Binh Province', 'hoa_binh'),
('19', N'Thái Nguyên', 'Thai Nguyen', N'Tỉnh Thái Nguyên', 'Thai Nguyen Province', 'thai_nguyen'),
('20', N'Lạng Sơn', 'Lang Son', N'Tỉnh Lạng Sơn', 'Lang Son Province', 'lang_son'),
('22', N'Quảng Ninh', 'Quang Ninh', N'Tỉnh Quảng Ninh', 'Quang Ninh Province', 'quang_ninh'),
('24', N'Bắc Giang', 'Bac Giang', N'Tỉnh Bắc Giang', 'Bac Giang Province', 'bac_giang'),
('25', N'Phú Thọ', 'Phu Tho', N'Tỉnh Phú Thọ', 'Phu Tho Province', 'phu_tho'),
('26', N'Vĩnh Phúc', 'Vinh Phuc', N'Tỉnh Vĩnh Phúc', 'Vinh Phuc Province', 'vinh_phuc'),
('27', N'Bắc Ninh', 'Bac Ninh', N'Tỉnh Bắc Ninh', 'Bac Ninh Province', 'bac_ninh'),
('30', N'Hải Dương', 'Hai Duong', N'Tỉnh Hải Dương', 'Hai Duong Province', 'hai_duong'),
('33', N'Hưng Yên', 'Hung Yen', N'Tỉnh Hưng Yên', 'Hung Yen Province', 'hung_yen'),
('34', N'Thái Bình', 'Thai Binh', N'Tỉnh Thái Bình', 'Thai Binh Province', 'thai_binh'),
('35', N'Hà Nam', 'Ha Nam', N'Tỉnh Hà Nam', 'Ha Nam Province', 'ha_nam'),
('36', N'Nam Định', 'Nam Dinh', N'Tỉnh Nam Định', 'Nam Dinh Province', 'nam_dinh'),
('37', N'Ninh Bình', 'Ninh Binh', N'Tỉnh Ninh Bình', 'Ninh Binh Province', 'ninh_binh'),

-- Tỉnh miền Trung
('38', N'Thanh Hóa', 'Thanh Hoa', N'Tỉnh Thanh Hóa', 'Thanh Hoa Province', 'thanh_hoa'),
('40', N'Nghệ An', 'Nghe An', N'Tỉnh Nghệ An', 'Nghe An Province', 'nghe_an'),
('42', N'Hà Tĩnh', 'Ha Tinh', N'Tỉnh Hà Tĩnh', 'Ha Tinh Province', 'ha_tinh'),
('44', N'Quảng Bình', 'Quang Binh', N'Tỉnh Quảng Bình', 'Quang Binh Province', 'quang_binh'),
('45', N'Quảng Trị', 'Quang Tri', N'Tỉnh Quảng Trị', 'Quang Tri Province', 'quang_tri'),
('46', N'Thừa Thiên Huế', 'Thua Thien Hue', N'Tỉnh Thừa Thiên Huế', 'Thua Thien Hue Province', 'thua_thien_hue'),
('49', N'Quảng Nam', 'Quang Nam', N'Tỉnh Quảng Nam', 'Quang Nam Province', 'quang_nam'),
('51', N'Quảng Ngãi', 'Quang Ngai', N'Tỉnh Quảng Ngãi', 'Quang Ngai Province', 'quang_ngai'),
('52', N'Bình Định', 'Binh Dinh', N'Tỉnh Bình Định', 'Binh Dinh Province', 'binh_dinh'),
('54', N'Phú Yên', 'Phu Yen', N'Tỉnh Phú Yên', 'Phu Yen Province', 'phu_yen'),
('56', N'Khánh Hòa', 'Khanh Hoa', N'Tỉnh Khánh Hòa', 'Khanh Hoa Province', 'khanh_hoa'),
('58', N'Ninh Thuận', 'Ninh Thuan', N'Tỉnh Ninh Thuận', 'Ninh Thuan Province', 'ninh_thuan'),
('60', N'Bình Thuận', 'Binh Thuan', N'Tỉnh Bình Thuận', 'Binh Thuan Province', 'binh_thuan'),
('62', N'Kon Tum', 'Kon Tum', N'Tỉnh Kon Tum', 'Kon Tum Province', 'kon_tum'),
('64', N'Gia Lai', 'Gia Lai', N'Tỉnh Gia Lai', 'Gia Lai Province', 'gia_lai'),
('66', N'Đắk Lắk', 'Dak Lak', N'Tỉnh Đắk Lắk', 'Dak Lak Province', 'dak_lak'),
('67', N'Đắk Nông', 'Dak Nong', N'Tỉnh Đắk Nông', 'Dak Nong Province', 'dak_nong'),
('68', N'Lâm Đồng', 'Lam Dong', N'Tỉnh Lâm Đồng', 'Lam Dong Province', 'lam_dong'),

-- Tỉnh miền Nam
('70', N'Bình Phước', 'Binh Phuoc', N'Tỉnh Bình Phước', 'Binh Phuoc Province', 'binh_phuoc'),
('72', N'Tây Ninh', 'Tay Ninh', N'Tỉnh Tây Ninh', 'Tay Ninh Province', 'tay_ninh'),
('74', N'Bình Dương', 'Binh Duong', N'Tỉnh Bình Dương', 'Binh Duong Province', 'binh_duong'),
('75', N'Đồng Nai', 'Dong Nai', N'Tỉnh Đồng Nai', 'Dong Nai Province', 'dong_nai'),
('77', N'Bà Rịa - Vũng Tàu', 'Ba Ria - Vung Tau', N'Tỉnh Bà Rịa - Vũng Tàu', 'Ba Ria - Vung Tau Province', 'ba_ria_vung_tau'),
('80', N'Long An', 'Long An', N'Tỉnh Long An', 'Long An Province', 'long_an'),
('82', N'Tiền Giang', 'Tien Giang', N'Tỉnh Tiền Giang', 'Tien Giang Province', 'tien_giang'),
('83', N'Bến Tre', 'Ben Tre', N'Tỉnh Bến Tre', 'Ben Tre Province', 'ben_tre'),
('84', N'Trà Vinh', 'Tra Vinh', N'Tỉnh Trà Vinh', 'Tra Vinh Province', 'tra_vinh'),
('86', N'Vĩnh Long', 'Vinh Long', N'Tỉnh Vĩnh Long', 'Vinh Long Province', 'vinh_long'),
('87', N'Đồng Tháp', 'Dong Thap', N'Tỉnh Đồng Tháp', 'Dong Thap Province', 'dong_thap'),
('89', N'An Giang', 'An Giang', N'Tỉnh An Giang', 'An Giang Province', 'an_giang'),
('91', N'Kiên Giang', 'Kien Giang', N'Tỉnh Kiên Giang', 'Kien Giang Province', 'kien_giang'),
('93', N'Hậu Giang', 'Hau Giang', N'Tỉnh Hậu Giang', 'Hau Giang Province', 'hau_giang'),
('94', N'Sóc Trăng', 'Soc Trang', N'Tỉnh Sóc Trăng', 'Soc Trang Province', 'soc_trang'),
('95', N'Bạc Liêu', 'Bac Lieu', N'Tỉnh Bạc Liêu', 'Bac Lieu Province', 'bac_lieu'),
('96', N'Cà Mau', 'Ca Mau', N'Tỉnh Cà Mau', 'Ca Mau Province', 'ca_mau');